apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-deployment
  namespace: cep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cep
  template:
    metadata:
      labels:
        app: cep
    spec:
      containers:
        - name: cep
          image: dellabeneta/cep:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"